### ISSUE TITLE
Records cannot be witnesses, but classes can

### ISSUE THREAD

**Issue by AArnott** [eiriktsarpalis/PolyType#54]
This generates a `GetShape<string>` method:

```cs
[GenerateShape<string>]
internal partial class Witness;
```

But this does _not_:

```cs
[GenerateShape<string>]
internal partial record Witness;
```

This took me several minutes of isolating and trying variances to figure out. There's no warning or error emitted (except where you try to use the witness and it fails).

**Comment by eiriktsarpalis** [comment]
Ultimately this stems from https://github.com/eiriktsarpalis/PolyType/issues/47. The current generation strategy requires that the witness type be a an empty class so that it can be populated with an `ITypeShapeProvider` implementation. Once #47 is resolved it should be possible to support witness generation for any kind that can implement interfaces.
